# Generated by Django 2.1 on 2024-05-31 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bum_tester', '0002_auto_20240530_1128'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.TextField()),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bum_tester.Answer')),
            ],
        ),
        migrations.RemoveField(
            model_name='pair',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='pair',
            name='question',
        ),
        migrations.DeleteModel(
            name='Pair',
        ),
    ]
